// <auto-generated />
namespace EWT_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changehallandaddbookingtomodelcs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changehallandaddbookingtomodelcs));
        
        string IMigrationMetadata.Id
        {
            get { return "202308282129313_changehall and add booking to model.cs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
